### ISSUE TITLE
🚨 registry.k8s.io affected by GCP europe-west9 outage 🚨 

### ISSUE THREAD

**Issue by Slach** [kubernetes/registry.k8s.io#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

Successfully pull `registry.k8s.io/sig-storage/livenessprobe:v2.4.0` from AWS EKS

### Debugging Information

Failed to pull image "registry.k8s.io/sig-storage/livenessprobe:v2.4.0": rpc error: code = Unknown desc = Error response from daemon: received unexpected HTTP status: 500 Internal Server Error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Slach** [comment]
docker pull registry.k8s.io/sig-storage/livenessprobe:v2.4.0
works ok in my local machine but doesn't work in AWS EKS

**Comment by Slach** [comment]
also got
```
Failed to pull image "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.1.0": rpc error: code = Unknown 
desc = Error response 
from daemon: error parsing HTTP 429 response body: 
invalid character '<' looking for beginning of value: 
"<html><body><h1>429 Too Many Requests</h1><p>Please reduce your request rate.</p></body></html>\n
```

**Comment by ameukam** [comment]
There is an ongoing incident affecting the `west-9` region: https://status.cloud.google.com/incidents/dS9ps52MUnxQfyDGPfkY.

We mostly rely on GCP services for `registry.k8s.io`.  We will provide an update as soon we have more informations.

**Comment by snahelou** [comment]
Hello

Do you know is there is any public mirror somewhere ?

Good luck for ppl who is impacted

BR

**Comment by SoulKyu** [comment]
Hello same error there ...
Did we have any proxy ?

**Comment by jredel** [comment]
Hello, same
`docker pull registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2 
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable`
but
`
docker pull k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
v4.0.2: Pulling from sig-storage/nfs-subdir-external-provisioner
Digest: sha256:63d5e04551ec8b5aae83b6f35938ca5ddc50a88d85492d9731810c31591fa4c9
Status: Image is up to date for k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
`
even if k8s.gcr.io should not be used any more, it can help.
https://kubernetes.io/blog/2023/03/10/image-registry-redirect/

**Comment by javabiien** [comment]
Until the issue is fixed, you can find some images here https://console.cloud.google.com/gcr/images/k8s-artifacts-prod
Example:
`eu.gcr.io/k8s-artifacts-prod/sig-storage/livenessprobe:v2.4.0`

**Comment by sichiba** [comment]
hello there,

we have the same issue while trying to pull image for Warning  Failed   24m (x6 over 50m)     kubelet  Failed to pull image "registry.k8s.io/ingress-nginx/controller:v1.5.1@sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629": rpc error: code = Unknown desc = failed to pull and unpack image "registry.k8s.io/ingress-nginx/controller@sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629": failed to resolve reference "registry.k8s.io/ingress-nginx/controller@sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629": pulling from host registry.k8s.io failed with status code [manifests sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629]: 503 Service Unavailable
  Normal   BackOff  4m3s (x243 over 66m)  kubelet  Back-off pulling image "registry.k8s.io/ingress-nginx/controller:v1.5.1@sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629"

**Comment by javabiien** [comment]
Hi @sichiba ,
I suggest you to try this uri `eu.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v1.5.1` look at https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/eu/ingress-nginx%2Fcontroller@sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629/details?tab=info

I use AWS EKS on eu-west-3 too and it worked for me. Also, I suggest you to make a backup of this image directly in your private AWS ECR registry if you have one.

**Comment by tommy31** [comment]
Same here in local or eu-west-3

**Comment by Joseph94m** [comment]
related [#1176](https://github.com/kubernetes/kubernetes/issues/117608)

**Comment by Joseph94m** [comment]
Btw pulling from k8s.gcr.io seems to work 🤷‍♂️

**Comment by 7ERr0r** [comment]
Funny how Kubernetes, made for high-availability is not high-available. 
Not to mention many bugs and terrible, slow golang code - 100% cpu all the time, especially on Raspberry PI.

**Comment by Joseph94m** [comment]
No matter how i change my configs, 
sudo kubeadm upgrade apply v1.22.17 will _always_ try to pull from registry.k8s.io, does anyone know how i can override that ?

**Comment by snahelou** [comment]
Or (a little bit durty) pull / tag images on each servers in order to use local cache registry. 

I did it for minikube and it saved my morning

```
minikube delete 
docker pull cnagent/coredns:v1.9.3 && docker tag cnagent/coredns:v1.9.3 eu.gcr.io/k8s-artifacts-prod/coredns:v1.9.3
docker pull calico/node:v3.24.5 && docker tag calico/node:v3.24.5 eu.gcr.io/k8s-artifacts-prod/node:v3.24.5
docker pull calico/cni:v3.24.5 && docker tag calico/cni:v3.24.5 eu.gcr.io/k8s-artifacts-prod/cni:v3.24.5
docker pull calico/kube-controllers:v3.24.5 && docker tag calico/kube-controllers:v3.24.5 eu.gcr.io/k8s-artifacts-prod/kube-controllers:v3.24.5
minikube start --image-repository=eu.gcr.io/k8s-artifacts-prod --kubernetes-version v1.25.3
```

**Comment by dims** [comment]
Folks, 
there are a bunch of options for mirroring etc that we have collected, please look:
https://github.com/kubernetes/registry.k8s.io/tree/main/docs/mirroring

**Comment by BenTheElder** [comment]
We're working on mitigating this.

> Funny how Kubernetes, made for high-availability is not high-available.
> Not to mention many bugs and terrible, slow golang code - 100% cpu all the time, especially on Raspberry PI.

This is not a helpful comment.
This registry is provided for free and run by volunteers doing it aside from their primary tasks.

> Was thinking of configuring the DNS server to resolve to some US CDN for registry.k8s.io.

To be clear: Please use your own mirror. We have a [detailed guide](https://github.com/kubernetes/registry.k8s.io/tree/main/docs/mirroring) here.

We may remove any particular backend at any time and the loadbalancing app we have in front is designed to cut costs dramatically. Using a particular backend directly and causing us excessive egress may result in enabling further countermeasures to block the offending traffic.

**Comment by BenTheElder** [comment]
> sudo kubeadm upgrade apply v1.22.17 will always try to pull from registry.k8s.io, does anyone know how i can override that ?

See the [mirroring guide](https://github.com/kubernetes/registry.k8s.io/tree/main/docs/mirroring) which has a kubeadm specific entry.

**Comment by BenTheElder** [comment]
@ameukam has removed the network endpoint group for europe-west9 from the LB.

This is our first major incident with registry.k8s.io. The application is in 20+ GCP regions and 10+ AWS regions but we currently have "route by region" w/o failover. Failing over could create cascading failure and/or dramatically increase the costs. We've only just gotten the Kubernetes project back to somewhat sustainably funded by avoiding a large chunk of our massive egress to AWS.

**Comment by BenTheElder** [comment]
Active discussion is in the SIG K8s-Infra slack at https://kubernetes.slack.com/archives/CCK68P2Q2/p1682496153874689

**Comment by BenTheElder** [comment]
GCP: europe-west3, europe-west6, europe-west12 appear to be routing around this fine at the moment.

GCP regions: europe-west1, europe-west2, europe-west4, europe-west8 we currently operate in and route 1:1, aside from europe-west9, so those regions should never have been impacted and don't appear to be (and regions outside of europe).

On AWS I don't have access to spin up things on demand and can't confirm yet discussing in the slack..

**Comment by BenTheElder** [comment]
> i need a replacement for this please.
>
> k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0

We don't have one advertised, you'll have to pull from another region and mirror (see above).

**Comment by BenTheElder** [comment]
AFAICT this remains isolated to vicinity of Paris, we're still investigating options to mitigate for this traffic, as the Paris datacenter outage is expected to be extended [^1]:
>  Water intrusion in europe-west9-a led to an emergency shutdown of some hardware in that zone. There is no current ETA for recovery of operations in europe-west9-a, but it is expected to be an extended outage 




Other traffic should remain unaffected, pulling from another region and mirroring to your own host should work for workloads near Paris.

[^1]: https://status.cloud.google.com/summary

**Comment by BenTheElder** [comment]
[Have been in SIG K8s Infra biweekly meeting and follow up meetings]

I'm not seeing 503s in the loadbalancer logs anymore newer than noon my time (2.5 hours ago), this may be resolved?
The 

I made some attempts at no-op changes to the GCLB earlier in attempt to force reprogramming.
Talking to some other Google employees with GCLB expertise currently to see what else we can / should do.

**Comment by BenTheElder** [comment]
I'm speaking with some other Google employees that are GCP Network Experts currently, we're looking into what's going on with the routing here.

**Comment by BenTheElder** [comment]
While the Network Endpoint Group was removed for europe-west9 the cloud run service was still available, and has been receiving traffic per the logs, we think that in the layers of routing that caused things to still try to reach it.

I've deleted the europe-west9 service now and we're seeing if that causes traffic to route to other regions properly.

Hopefully next time we'll have a playbook we can follow based on this time.

**Comment by BenTheElder** [comment]
We also have Cloud CDN enabled on this loadbalancer which doesn't make sense given we serve almost exclusively redirects, it has cached some errors ... I've disabled that and the loadbalancer is reprogramming currently.

When we have this sorted out we'll follow-up with reconciling the terraform config. For now clickops to get things running smoothly again.

**Comment by BenTheElder** [comment]
The backend service resource seemed to be stuck, so we've created a new the backend service and pointed the url-map at it. This time with CDN. I've been on a call with a GCP Network Support Engineer and @aojea looking into this still and taking notes for next time.

We think our BES got wedged with the outage.

**Comment by BenTheElder** [comment]
We _think_ this is may be fixed from the logs, but it's early yet and we need confirmation from outside of GCP/Google in Paris area. Asked in the slack for now. Stepping away for a bit.

**Comment by tzneal** [comment]
I just verified from eu-west-3 which is Paris. From there crane hitting a registry.k8s.io image is pulling from europe-west1-docker.pkg.dev:

```
023/04/27 00:21:51 --> GET https://registry.k8s.io/v2/
2023/04/27 00:21:51 GET /v2/ HTTP/1.1
Host: registry.k8s.io
User-Agent: crane/3706061a683bf461511f2691ceec78cab4757093 go-containerregistry/(devel)
Accept-Encoding: gzip


2023/04/27 00:21:51 <-- 200 https://registry.k8s.io/v2/ (35.154209ms)
2023/04/27 00:21:51 HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: text/html
Date: Thu, 27 Apr 2023 00:21:51 GMT
Docker-Distribution-Api-Version: registry/2.0
Server: Google Frontend
Via: 1.1 google
X-Cloud-Trace-Context: 6f4bc9ee5f4ea0c2d48d8295bcf9c5fd
Content-Length: 0


2023/04/27 00:21:51 --> GET https://registry.k8s.io/v2/pause/manifests/3.8
2023/04/27 00:21:51 GET /v2/pause/manifests/3.8 HTTP/1.1
Host: registry.k8s.io
User-Agent: crane/3706061a683bf461511f2691ceec78cab4757093 go-containerregistry/(devel)
Accept: application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.imaglication/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json
Accept-Encoding: gzip


2023/04/27 00:21:51 <-- 307 https://registry.k8s.io/v2/pause/manifests/3.8 (12.587526ms)
2023/04/27 00:21:51 HTTP/2.0 307 Temporary Redirect
Content-Length: 120
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: text/html; charset=utf-8
Date: Thu, 27 Apr 2023 00:21:51 GMT
Location: https://europe-west1-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.8
Server: Google Frontend
Via: 1.1 google
X-Cloud-Trace-Context: f5090c1669b2698c87b59b0e418a1314

<a href="https://europe-west1-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.8">Temporary Redirect</a>.
```

I pulled the image 100 times with no issues. LGTM.

**Comment by BenTheElder** [comment]
:thank-you: Tentative close but still monitoring this and will be doing linking followups ...

**Comment by TerryHowe** [comment]
Downloader worked fine for me in Paris
```
Averages:
registry.k8s.io/cluster-api-nested/cluster-api-nested-controller:v0.1.0   410.545333ms
registry.k8s.io/ingress-nginx/controller:v1.7.0   1.42553222s
registry.k8s.io/pause:3.9   214.246905ms
us.gcr.io/k8s-artifacts-prod/cluster-api-nested/cluster-api-nested-controller:v0.1.0   1.137680131s
us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v1.7.0   2.388210114s
us.gcr.io/k8s-artifacts-prod/pause:3.9   695.360459ms
```

**Comment by BenTheElder** [comment]
# Postmortem

## Background

registry.k8s.io currently involves a set of GCP Cloud Run regional instances behind a GCLB as the front line OCI Distribution API response, which then redirects to assorted backing stores.

One of the regions we've been operating in is europe-west9 (GCP Paris, France).

## Cause

Due to [the europe-west9 GCP incident](https://status.cloud.google.com/incidents/dS9ps52MUnxQfyDGPfkY) (flooded datacenter), traffic in the proximity of Paris was routed to failing backends. Cloud Run and other services had outages in this region due to the datacenter flooding and continue to have issues.


First attempts at mitigating involved @ameukam removing europe-west9 network endpoint group from the default backend endpoint service (henceforth: "BES") behind registry.k8s.io. This threw some errors but then appeared to work.

However, further interactions showed the BES resource to be not-ready. GCLB is one of the known affected services.

It appears, as an end user, that GCLB state for the registry.k8s.io default backend service wedged and got out of sync with configuration updates during this outage.

Also, Serverless network endpoint groups do not have healthchecks support, however I _think_ we would have seen failover if we'd removed the cloud run service instaed of only removing it from the network endpoint groups in the BES.

https://cloud.google.com/load-balancing/docs/negs/serverless-neg-concepts#backend-service-limitations

## Mitigation

1. Recreate the backend endpoint service with a new name, and without the affected region.
2. Update the GCLB URL Map to point to the new BES.
3. Shut down the affected cloud run region, it's not helping anything, debugging will be easier with no broken backend to route to with stale 

Additionally, we had Cloud CDN enabled on the GCLB for some reason. This isn't helpful under normal circumstances as we serve client-IP specific responses to optimize traffic, and our response are small redirects.
Worse, it was harmful as some failed requests got cached. In 1) I also disabled Cloud CDN on the new BES once we figured out that creating a new BES would bypass synchronization issues with the existing BES versus attempting to disable it on the existing BES.

We should not enable Cloud CDN on this application, otherwise in the future if we run into a broken cloud run region due to a major incident like this we can retry 1,2,3 to remove it and route around.

## What Went Poorly

1. My iPhone crashed this morning leaving me unreachable until I woke up and noticed 🙃 
2. It took much longer than I'd like to root cause and mitigate this. We have more contacts to reach out to in the future and a better understanding of where things can go wrong, after arguably our first "major" incident.
3. GCLB updates getting wedged. Apparently in the future we can sidestep this sort of thing by creating new BES without trying to reprogram the existing one. BES have most of the configuration and we can pivot to the new BES relatively quickly if we take that approach instead of banging our heads against issues with the existing one.

## What Went Well

1. We have global contributors and @ameukam was around to respond this morning.
2. The vast majority of our global traffic was unaffected. Most of our infrastructure and routing is region-local and continued to function uninterrupted.
3. We have more than sufficient logs and monitoring to identify and debug incidents like this. We need more preparation to act on them effectively. 
5. We were able to obtain extensive help from highly knowledgable support engineers once we pinged the right people. I'll be making sure Googlers involved with the SIG know how to reach out in the future.


## Follow-Up Work

1. @BenTheElder: Reconcile configured terraform in github.com/kubernetes/k8s.io with emergency clickops fixes from today.
2. @BenTheElder: Make sure all admins know about effective mitigation steps for next time.
3. @BenTheElder: Make sure K8s Infra Googlers know how to best to reach out to support contacts for help with future issues. We received immensely helpful suggestions once we got in touch with GCP networking experts.
6. Carefully investigate automated failover options. We need to be careful with this to avoid cascading failure and spikes in egress costs. We *intentionally* serve traffic only from the local copy whenever possible as a major cost control measure.
7. Revisit expanding to more regions, to further limit failure domains. From a cost-effectiveness standpoint we want to be in essentially all regions we have usage in as bandwidth generally exceeds storage costs, but we've been limited by rate limit issues with https://github.com/kubernetes-sigs/promo-tools and hesitant to add more regions. This needs revisting.

**Comment by BenTheElder** [comment]
# Follow-Up Work Update

1: In Progress ...
2: ✅ 
3. ✅ 
4. The "Classic" GCLB doesn't have a great answer for this when using serverless network endpoint groups AFAICT (you can scale to zero or remove the endpoint group as we did here which would ordinarily work fine ... we had other complications), but the [new GCLBs with envoy](https://cloud.google.com/load-balancing/docs/choosing-load-balancer#proxy-pass-through) (`loadBalancingScheme: EXTERNAL_MANAGED` instead of `loadBalancingScheme: EXTERNAL`) have support for "[outlier detection](https://cloud.google.com/load-balancing/docs/https/setting-up-global-traffic-mgmt#configure_outlier_detection)" that we could use here.  Thanks @jimangel 🙏 
5. Long term ... will have to come back to that
6. ✅  (@aojea narrowly beat me to it :-))

**Comment by BenTheElder** [comment]
# Follow-Up Work Update

Regarding 1)
We can see that the AR backends have recovered in europe-west9:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-k8sio-cip

Per the incident status page, B and C zones are recovered for Cloud Run and GCLB as well, and we're seeing europe-west9 healthy in the registry staging instance, so we may not need to drop it from terraform and can consider instead bringing the region back online.

For now I'm filing a much smaller diff to disable Cloud CDN which we'll automatically deploy to staging and continuing to look into 4) to test in staging. 

Holding off on if we should drop europe-west9 from staging or bring it back online now that things are looking healthy enough.



Regarding 5)
I filed #236 to track 5) going forward. We have also #172 #194 related issues.

**Comment by SergeyKanzhelev** [comment]
> 4\. Carefully investigate automated failover options. We need to be careful with this to avoid cascading failure and spikes in egress costs. We _intentionally_ serve traffic only from the local copy whenever possible as a major cost control measure.

This made me think - registry today has more or less predictable redirects. So if there will be some failover, those assumptions may break and people took dependency on those predictable redirects may break even with the failover.

I wonder if one of the follow up action may be to randomly redirect to failover 1 out of million requests, or 1 day of the month, or something like this? Or even direct to other cloud, not simply to the failover. So those dependencies will be uncovered by people using this registry earlier.

**Comment by BenTheElder** [comment]
> This made me think - registry today has more or less predictable redirects. So if there will be some failover, those assumptions may break and people took dependency on those predictable redirects may break even with the failover.

This is documented at the top of the readme at https://registry.k8s.io and in all the communications etc:

https://github.com/kubernetes/registry.k8s.io#stability

We **do not support relying on this** and they're only predictable-ish until the next infrastructure change. For example currently users that were affected by this issue are being redirected to a different location right now, or in the past months as we've added new regions. Or switching services entirely such as #194 

If people take a dependency on what's behind the redirects, we may outright block that in the future e.g. by only using signed url redirects or other means, and we will not hesitate to enact break that behavior. It's not cost effective for users to directly depend on backing stores that we may need to migrate in the future and we've been very clear that we will not support this.

We've had some discussion of making the backing stores more opaque, it's on the backlog as we rely on users to be somewhat well behaved today, but we can and will move these around in the future for other reasons anyhow.

> I wonder if one of the follow up action may be to randomly redirect to failover 1 out of million requests, or 1 day of the month, or something like this? Or even direct to other cloud, not simply to the failover. So those dependencies will be uncovered by people using this registry earlier.

I'm not sure I gather this correctly, but I don't see how this helps?

Note: For architectural and security reasons not all requests can go to AWS instead of GCP, that's a complicated topic I'd rather not attempt to re-tread on this thread but our docs cover this a bit.

So the question here is of automatic region failover, I've thought about it more and the cost implications of that should largely be fine, for traffic we can identify we already redirect independent of the AR region, so the egress costs will go up for some subset of traffic that we don't identify as AWS but serve from AWS in-region correctly by GCP region proximity, which should be a small portion.

The cascading failure concerns remain. We have regional capacity constraints so automatic failover has to be limited.

**Comment by SergeyKanzhelev** [comment]
> > I wonder if one of the follow up action may be to randomly redirect to failover 1 out of million requests, or 1 day of the month, or something like this? Or even direct to other cloud, not simply to the failover. So those dependencies will be uncovered by people using this registry earlier.
> 
> I'm not sure I gather this correctly, but I don't see how this helps?

If the switch to failover happens periodically, we will test that failover works and anybody who took the unwanted behavior will discover this dependency earlier than the next outage.

**Comment by BenTheElder** [comment]
> If the switch to failover happens periodically, we will test that failover works [...]

Er, but the problem here isn't how we redirected requests, it was GCLB routing to instances in a region experiencing an outage. So altering our redirects wouldn't test this and the failover between regions would be some other process.

Also, testing region failover without an actual outage would not have caught the issues with updating GCLB, which we now know how to workaround if that occurs again, even though it's unlikely.

If we have active probing with removing regions, we will of course test that, but only to ensure that it works breifly.

>  [...] and anybody who took the unwanted behavior will discover this dependency earlier than the next outage.

We can accomplish this without paying the cost of switching regions just by changing the names of the endpoints / obscuring the details or restricting access of direct dependencies (e.g. signed URLs).

But we also don't need to optimize for this, because this is well-communicated unsupported behavior. We don't document these backends and choosing to depend on them without looking at our docs or any of the communication is not a reasonable choice we should optimize for.

If users are broken by us changing the backends in the future, the answer is the same as https://kubernetes.io/blog/2023/03/10/image-registry-redirect/#i-am-impacted-what-should-i-do
And will not prevent us from doing what we need to do.

**Comment by BenTheElder** [comment]
I think we should be able to manually drop regions and shed traffic away from them faster next time now that we have this experience and understand workarounds better, but automatic cutover options are definitely being investigated. 

In the shorter term 1) is prioritized and I'm doing some more testing to confirm if we should drop europe-west9 from the terraform desired state or re-deploy it when we sync everything back.

**Comment by BenTheElder** [comment]
Thanks to @ameukam I can now run test instances in AWS and I can confirm that our staging instance which is still running in GCP europe-west9 works fine currently, pulling an image through the staging instance from eu-west-3 in AWS pulls via europe-west9 without issues.

Will plan to roll forward and test + monitor.

**Comment by BenTheElder** [comment]
Also filed b/279998015 (internal bug) regarding the unready BES.

**Comment by BenTheElder** [comment]
This is deployed.

**Comment by BenTheElder** [comment]
europe-west9 has been brought back online for the registry, while zone A has issues for some services still we're only using regional/global endpoints.

I've tested with an eu-west-3 EC2 VM and it's pulling through europe-west9 without issue.

Now that prod is fully reconciled with other changes we'd been soaking in staging, will resume looking into further improvements.

**Comment by BenTheElder** [comment]
Small update: We had some other things come up, but we're making progress migrating to the newer envoy based GCLBs which should give us access to new features for integrating with serverless network endpoint groups https://github.com/kubernetes/k8s.io/pull/5249 and prior cross-linked PRs.

While we're at it we've migrated to Certificate Manager and ACME DNS challenge based certs instead of the existing managed SSL (based on HTTP challenge) to streamline this sort of migration going forward.

I've also added this incident post-mortem as a topic on the agenda for tomorrow's SIG K8s Infra biweekly meeting.
