### ISSUE TITLE
Getting 403 from node (ssh host) with curl

### ISSUE THREAD

**Issue by gigo1980** [kubernetes/registry.k8s.io#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

There should be an redirect.
```sh
curl https://registry.k8s.io/v2/metrics-server/metrics-server/blobs/sha256:817bbe3f2e5179b5fa7dd4085c87aab1faaf9dc879e3b1d05796901a006f58ab
<a href="https://prod-registry-k8s-io-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com/containers/images/sha256:817bbe3f2e5179b5fa7dd4085c87aab1faaf9dc879e3b1d05796901a006f58ab">Temporary Redirect</a>.
```

### Debugging Information

On one node of cluster I receive the following error.
```sh
curl https://registry.k8s.io/v2/metrics-server/metrics-server/blobs/sha256:817bbe3f2e5179b5fa7dd4085c87aab1faaf9dc879e3b1d05796901a006f58ab

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v2/metrics-server/metrics-server/blobs/sha256:817bbe3f2e5179b5fa7dd4085c87aab1faaf9dc879e3b1d05796901a006f58ab</code> from this server.</h2>
<h2></h2>
</body></html>
```

### Anything else?

Is there a IP Blacklist?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenTheElder** [comment]
This is covered in the debugging guide and past issues:

https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md#debugging-issues-with-registryk8sio

**Comment by fatelgit** [comment]
I know this ain't your fault but I would like to add that this is an incredibly annoying issue because google is giving zero f* about small hosters and we are dealing with that almost every day. In cloud hosting environments where servers can and will be abused (even for a short period of time) it will happen very often that ip addresses get blacklisted by google. And it is really hard to get unbanned.
However we are not having any issues with other registries like docker hub  - so maybe just maybe you could consider moving to another public registry because banning  ips from cloud providers is a really stupid thing to do. Imagine amazon/microsoft would start to block google machines on a network level...

**Comment by dims** [comment]
@fatelgit please be [respectful](https://github.com/cncf/foundation/blob/main/code-of-conduct.md#our-standards) here.

**Comment by fatelgit** [comment]
Sorry for being a bit blunt about this topic - I've updated my previous message. Thanks for the hint about mirroring, I will look into it.

**Comment by BenTheElder** [comment]
Hosting these images is **very** expensive and we're not in a position to dictate cloud provider policy.

If anyone wants to step up and work on alternate hosting, please see https://github.com/kubernetes/registry.k8s.io#community-discussion-contribution-and-support for info on SIG K8s Infra.

**Comment by mrbobbytables** [comment]
I know its not the answer you want to hear, but as there isn't really anything further actionable we can do on the project side of things, I am going to go ahead and close this out.

If you need help setting up a mirror, please start with the guide @dims links earlier and if you need further assistance, #kubernetes-users in K8s slack would be my next stop. 👍
