### ISSUE TITLE
error docker pull

### ISSUE THREAD

**Issue by Test45o** [kubernetes/registry.k8s.io#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

Hello 

I have creates a repository remote docker he go ping to this website : https://registry.k8s.io/

and after i execute this commande : 

1. docker login link_artifactory
2. docker pull link_artifactory/name_repo/kube-state-metrics/kube-state-metrics:v2.6.0

and i have this error : 

error pulling image configuration: download failes after attempts=1 unknown blob

have you idea ? 

Other informations : 
version docker : 24.0.6

Thanks in advance

### Debugging Information

error pulling image configuration: download failes after attempts=1 unknown blob

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrbobbytables** [comment]
As this looks to be an issue with artifactory and not registry.k8s.io, I am going to go ahead and close this out. If further investigation points back towards registry.k8s.io being the problem, please go ahead and reopen the issue. 👍

**Comment by FilipeNas** [comment]
Had the same error mirroring from JFrog Artifactory.
Because we only had whitelisted https://registry.k8s.io/, and none of the CDNs behind it.

Reading the documentation, we can use crane to find the URLs of the CDNs needed to be whitelisted.
https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md#verify-image-pulls

Even though we can find the needed URLs, I would like to have static list (docs) of the CDNs URLs, because our instance can me migrated to another region and target other CDNs URLs that are not whitelisted.

Also, i found all the FQDN (i hope) of the CDNs / s3 buckets to allow https://github.com/kubernetes/k8s.io/blob/main/infra/gcp/terraform/modules/oci-proxy/main.tf

ping @mrbobbytables @BenTheElder
